version: '3.8'

services:
  # 标准 Redis 实例 - 用于 Redis Insight 连接
  redis-standalone:
    image: redis:7-alpine
    container_name: redis-standalone
    command: redis-server --port 6379 --appendonly no --save ""
    ports:
      - "6379:6379"
    networks:
      - redis-cluster

  # Redis 主节点
  redis-master-1:
    image: redis:7-alpine
    container_name: redis-master-1
    command: redis-server --port 7001 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly no --save "" --bind 0.0.0.0
    ports:
      - "7001:7001"
    networks:
      - redis-cluster

  redis-master-2:
    image: redis:7-alpine
    container_name: redis-master-2
    command: redis-server --port 7002 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly no --save "" --bind 0.0.0.0
    ports:
      - "7002:7002"
    networks:
      - redis-cluster

  redis-master-3:
    image: redis:7-alpine
    container_name: redis-master-3
    command: redis-server --port 7003 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly no --save "" --bind 0.0.0.0
    ports:
      - "7003:7003"
    networks:
      - redis-cluster

  redis-master-4:
    image: redis:7-alpine
    container_name: redis-master-4
    command: redis-server --port 7004 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly no --save "" --bind 0.0.0.0
    ports:
      - "7004:7004"
    networks:
      - redis-cluster

  redis-master-5:
    image: redis:7-alpine
    container_name: redis-master-5
    command: redis-server --port 7005 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly no --save "" --bind 0.0.0.0
    ports:
      - "7005:7005"
    networks:
      - redis-cluster

  redis-master-6:
    image: redis:7-alpine
    container_name: redis-master-6
    command: redis-server --port 7006 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly no --save "" --bind 0.0.0.0
    ports:
      - "7006:7006"
    networks:
      - redis-cluster

  redis-master-7:
    image: redis:7-alpine
    container_name: redis-master-7
    command: redis-server --port 7007 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly no --save "" --bind 0.0.0.0
    ports:
      - "7007:7007"
    networks:
      - redis-cluster

  redis-master-8:
    image: redis:7-alpine
    container_name: redis-master-8
    command: redis-server --port 7008 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly no --save "" --bind 0.0.0.0
    ports:
      - "7008:7008"
    networks:
      - redis-cluster

  # Redis 从节点
  redis-slave-1:
    image: redis:7-alpine
    container_name: redis-slave-1
    command: redis-server --port 8001 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly no --save "" --bind 0.0.0.0
    ports:
      - "8001:8001"
    networks:
      - redis-cluster

  redis-slave-2:
    image: redis:7-alpine
    container_name: redis-slave-2
    command: redis-server --port 8002 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly no --save "" --bind 0.0.0.0
    ports:
      - "8002:8002"
    networks:
      - redis-cluster

  redis-slave-3:
    image: redis:7-alpine
    container_name: redis-slave-3
    command: redis-server --port 8003 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly no --save "" --bind 0.0.0.0
    ports:
      - "8003:8003"
    networks:
      - redis-cluster

  redis-slave-4:
    image: redis:7-alpine
    container_name: redis-slave-4
    command: redis-server --port 8004 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly no --save "" --bind 0.0.0.0
    ports:
      - "8004:8004"
    networks:
      - redis-cluster

  redis-slave-5:
    image: redis:7-alpine
    container_name: redis-slave-5
    command: redis-server --port 8005 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly no --save "" --bind 0.0.0.0
    ports:
      - "8005:8005"
    networks:
      - redis-cluster

  redis-slave-6:
    image: redis:7-alpine
    container_name: redis-slave-6
    command: redis-server --port 8006 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly no --save "" --bind 0.0.0.0
    ports:
      - "8006:8006"
    networks:
      - redis-cluster

  redis-slave-7:
    image: redis:7-alpine
    container_name: redis-slave-7
    command: redis-server --port 8007 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly no --save "" --bind 0.0.0.0
    ports:
      - "8007:8007"
    networks:
      - redis-cluster

  redis-slave-8:
    image: redis:7-alpine
    container_name: redis-slave-8
    command: redis-server --port 8008 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly no --save "" --bind 0.0.0.0
    ports:
      - "8008:8008"
    networks:
      - redis-cluster

  # Redis 集群初始化容器
  redis-cluster-init:
    image: redis:7-alpine
    container_name: redis-cluster-init
    depends_on:
      - redis-master-1
      - redis-master-2
      - redis-master-3
      - redis-master-4
      - redis-master-5
      - redis-master-6
      - redis-master-7
      - redis-master-8
      - redis-slave-1
      - redis-slave-2
      - redis-slave-3
      - redis-slave-4
      - redis-slave-5
      - redis-slave-6
      - redis-slave-7
      - redis-slave-8
    command: |
      sh -c '
        echo "等待Redis节点启动..."
        sleep 15
        
        echo "创建Redis集群..."
        redis-cli --cluster create \
          127.0.0.1:7001 \
          127.0.0.1:7002 \
          127.0.0.1:7003 \
          127.0.0.1:7004 \
          127.0.0.1:7005 \
          127.0.0.1:7006 \
          127.0.0.1:7007 \
          127.0.0.1:7008 \
          127.0.0.1:8001 \
          127.0.0.1:8002 \
          127.0.0.1:8003 \
          127.0.0.1:8004 \
          127.0.0.1:8005 \
          127.0.0.1:8006 \
          127.0.0.1:8007 \
          127.0.0.1:8008 \
          --cluster-replicas 1 \
          --cluster-yes
        
        echo "集群创建完成！"
        echo "标准Redis实例端口: 6379 (用于Redis Insight)"
        echo "主节点端口: 7001-7008"
        echo "从节点端口: 8001-8008"
      '
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge