# Master节点配置
server:
  port: 8080

spring:
  application:
    name: master-node

# Redis集群配置
redis:
  cluster:
    nodes: localhost:7001,localhost:7002,localhost:7003,localhost:7004,localhost:7005,localhost:7006,localhost:7007,localhost:7008
    password: 
    timeout: 5000
    max-redirects: 3
  jedis:
    pool:
      max-active: 20
      max-idle: 10
      min-idle: 5
      max-wait: 3000

# 监控配置
monitor:
  report-interval: 30000
  health-check-timeout: 5000

# 部署配置
deploy:
  master:
    workspace: /tmp/deploy/workspace
    build: /tmp/deploy/build
    distribute: /tmp/deploy/distribute
    backup: /tmp/deploy/backup
    logs: /tmp/deploy/logs
  jar-backup-dir: /tmp/backup
  jar-deploy-dir: /tmp/services
  jar-shared-dir: /tmp/shared/jars
  max-backup-versions: 5
  
  git:
    workspace: /Users/lm/Documents/projects
    default-branch: dev
    username: g-test
    password: Pass123!
    
  build:
    output-dir: /tmp/build-output
    maven-home: /opt/homebrew/Cellar/maven/3.9.11/libexec

# 文件分发配置
file-distribution:
  shared-storage:
    enabled: true
    path: /tmp/shared/storage
  http-server:
    enabled: true
    port: 8081
    base-path: /tmp/http-files
  redis:
    enabled: false
    max-file-size: 10485760  # 10MB

# 服务配置
services:
  - name: service-a
    jar-name: service-a.jar
    jar-path: /tmp/services/service-a.jar
    target-nodes: ["agent-1", "agent-2"]
    description: "服务A"
  - name: service-b
    jar-name: service-b.jar
    jar-path: /tmp/services/service-b.jar
    target-nodes: ["agent-1", "agent-3"]
    description: "服务B"

# Springfox配置
springfox:
  documentation:
    swagger-ui:
      enabled: true
    enabled: true

# 日志配置
logging:
  file:
    name: logs/master.log
  level:
    com.redis.jedis: INFO
    root: INFO
