# Agent节点配置
server:
  port: 8081

spring:
  application:
    name: agent-node
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  
  # Redis配置（支持 spring.redis.* 单机形式）
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 
    timeout: 5000
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 3000

# 节点标识
node:
  id: node001
  name: Agent Node 001

 

# 监控配置
monitor:
  report-interval: 30000
  health-check-timeout: 5000

# 部署配置
deploy:
  agent:
    workspace: /opt/agent/workspace
    services: /opt/agent/services
    backup: /opt/agent/backup
    logs: /opt/agent/logs
  jar-backup-dir: /opt/backup
  jar-deploy-dir: /opt/services
  jar-shared-dir: /opt/shared/jars

# 服务管理配置
service-management:
  auto-recovery: true
  health-check-interval: 30000
  max-retry-attempts: 3
  process-timeout: 30000

# 文件接收配置
file-receive:
  shared-storage:
    enabled: true
    path: /opt/shared/storage
  http-download:
    enabled: true
    timeout: 300000  # 5分钟
  temp-dir: /tmp/agent-downloads

# 日志配置
logging:
  file:
    name: logs/agent.log
  level:
    com.redis.jedis: INFO
    root: INFO
